### ISSUE TITLE
How can i contact you ?

### ISSUE THREAD

**Issue by sdeseille** [leto/math--matrixreal#14]
Hello Leto

I send you an email but have no response.
Can you take a look in your mailbox. :)

I joined the cpan pull request challenge and i wish to work on submatrix documentation.

regards

sdeseille

**Comment by leto** [comment]
I didn't see your email! This is actually the best place, anyway. You are very encouraged to work on submatrix documentation! :+1: Please create a branch from the master branch to start on that. Please let me know if you have questions.

**Comment by leto** [comment]
Closing this for now, feel free to create other issue or PR's
