### ISSUE TITLE
Bug report for as_list() method.

### ISSUE THREAD

**Issue by stdiff** [leto/math--matrixreal#16]
I would like to report a bug of ver2.12.

Description:
as_list() method gives the wrong list if a given matrix is not a square matrix.

Code for reproduce:

    #!/usr/bin/perl 
    use strict;
    use warnings;
    use Math::MatrixReal;

    my $M = Math::MatrixReal->new_from_rows([[1,2,3],[4,5,6]]);
    print $M;
    my @list = $M->as_list;
    print "@list";
    exit;

Result:

    [  1.000000000000E+00  2.000000000000E+00  3.000000000000E+00 ]
    [  4.000000000000E+00  5.000000000000E+00  6.000000000000E+00 ]
    1 2 4 5

Expected result:

    [  1.000000000000E+00  2.000000000000E+00  3.000000000000E+00 ]
    [  4.000000000000E+00  5.000000000000E+00  6.000000000000E+00 ]
    1 2 3 4 5 6

Where to fix:

    --- Math-MatrixReal-2.12/lib/Math/MatrixReal.pm 2014-12-28 15:00:05.000000000 +0100
    +++ Math-MatrixReal-2.12.patched/lib/Math/MatrixReal.pm 2015-09-01 03:28:34.445485459 +0200
    @@ -657,7 +657,7 @@ sub as_list
         my($rows,$cols) = ($self->[1], $self->[2]);
         my @list;
         for(my $i = 0; $i < $rows; $i++ ){
    -        for(my $j = 0; $j < $rows; $j++){
    +        for(my $j = 0; $j < $cols; $j++){
                 push @list, $self->[0][$i][$j];
             }
         }

**Comment by leto** [comment]
Thanks! Can you add a test and submit this as a Pull Request? I am actually in the hospital right now and won't be able to get to this for a while.

**Comment by stdiff** [comment]
I did. Get soon well!

**Comment by leto** [comment]
This is fixed now.
