### ISSUE TITLE
Vertical Concatenation

### ISSUE THREAD

**Issue by ambs** [leto/math--matrixreal#5]
Although there is an horizontal concatenation, there isn't a vertical one. A possibility would be to transpose them, concatenate, transpose again. But this is time consuming.

Is there a better way?

In fact, I just want to add an element to the first position of a (possible long) vertical vector.

Thanks

**Comment by leto** [comment]
@ambs Is this still a valid issue?

**Comment by ambs** [comment]
I would like to look into it again, yes. So, if you do not mind leaving the issue open some more time, I would thank you.

**Comment by leto** [comment]
@ambs ping. Are you still interested in implementing this?

**Comment by ambs** [comment]
No idea. Just close it :-)
